version: 2.1
orbs:
  android: circleci/android@3.0.2
  ruby: circleci/ruby@2.3.0
jobs:
  build-android:
    docker:
      - image: cimg/android:2024.11.1
    steps:
      - checkout
      - run: sudo gem install fastlane
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane playstore
  build-ios:
    macos:
      xcode: 14.3.1
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane test
workflows:
  build-deploy:
    jobs:
      - build-android
      - build-ios