ALTER TABLE "FinanceConfig"
ADD COLUMN "snackEurMinor" INTEGER NOT NULL DEFAULT 129,
ADD COLUMN "standardEurMinor" INTEGER NOT NULL DEFAULT 179,
ADD COLUMN "premiereEurMinor" INTEGER NOT NULL DEFAULT 229,
ADD COLUMN "familyPassEurMinor" INTEGER NOT NULL DEFAULT 900;
