ALTER TABLE "Video"
  ADD COLUMN IF NOT EXISTS "taxRevenueShare" DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE "VideoTechnicalMetadata"
  ADD COLUMN IF NOT EXISTS "availabilityRegion" TEXT NOT NULL DEFAULT 'GLOBAL';
