DO $$
BEGIN
  ALTER TYPE "VideoStatus" ADD VALUE IF NOT EXISTS 'MASTER_UPLOADED';
  ALTER TYPE "VideoStatus" ADD VALUE IF NOT EXISTS 'PROCESSING';
  ALTER TYPE "VideoStatus" ADD VALUE IF NOT EXISTS 'HLS_UPLOADED';
  ALTER TYPE "VideoStatus" ADD VALUE IF NOT EXISTS 'READY';
  ALTER TYPE "VideoStatus" ADD VALUE IF NOT EXISTS 'PUBLISHED';
  ALTER TYPE "VideoStatus" ADD VALUE IF NOT EXISTS 'ARCHIVED';
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

ALTER TABLE "Video"
  ADD COLUMN IF NOT EXISTS "hlsUrl" TEXT,
  ADD COLUMN IF NOT EXISTS "hlsVersion" TEXT,
  ADD COLUMN IF NOT EXISTS "qualities" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN IF NOT EXISTS "unlockPrice" INTEGER,
  ADD COLUMN IF NOT EXISTS "producerRevenueShare" DOUBLE PRECISION NOT NULL DEFAULT 70,
  ADD COLUMN IF NOT EXISTS "platformRevenueShare" DOUBLE PRECISION NOT NULL DEFAULT 30,
  ADD COLUMN IF NOT EXISTS "isPublished" BOOLEAN NOT NULL DEFAULT false;

UPDATE "Video"
SET "qualities" = ARRAY[]::TEXT[]
WHERE "qualities" IS NULL;

ALTER TABLE "Video"
  ALTER COLUMN "qualities" SET DEFAULT ARRAY[]::TEXT[],
  ALTER COLUMN "qualities" SET NOT NULL;

ALTER TABLE "CreatorProfile"
  ADD COLUMN IF NOT EXISTS "uploadAccessToken" TEXT,
  ADD COLUMN IF NOT EXISTS "uploadAccessTokenExpiresAt" TIMESTAMP(3);

ALTER TABLE "VideoTechnicalMetadata"
  ADD COLUMN IF NOT EXISTS "masterKey" TEXT,
  ADD COLUMN IF NOT EXISTS "masterFileName" TEXT,
  ADD COLUMN IF NOT EXISTS "masterFileSize" INTEGER,
  ADD COLUMN IF NOT EXISTS "masterUploadedAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "masterUploadKey" TEXT,
  ADD COLUMN IF NOT EXISTS "masterProcessingStatus" TEXT,
  ADD COLUMN IF NOT EXISTS "processingStatus" TEXT NOT NULL DEFAULT 'NO_MASTER',
  ADD COLUMN IF NOT EXISTS "encodingStartedAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "encodingCompletedAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "hlsUploadedAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "hlsPlaybackUrl" TEXT,
  ADD COLUMN IF NOT EXISTS "hlsVerifiedAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "readyToStreamAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "playbackUrl" TEXT;

UPDATE "VideoTechnicalMetadata"
SET "processingStatus" = 'NO_MASTER'
WHERE "processingStatus" IS NULL;

ALTER TABLE "VideoTechnicalMetadata"
  ALTER COLUMN "processingStatus" SET DEFAULT 'NO_MASTER',
  ALTER COLUMN "processingStatus" SET NOT NULL;
